mappings:
  - match: .bash(\w)*
    target_os:
      - "Linux"
      - "Darwin"

modules:
  # other useful stuff
  - repo: git@github.com:tmux-plugins/tpm.git
    pull_only: true
    link: none
    location: ~/.config/tmux/plugins/tpm
    name: tpm
  - repo: git@github.com:junegunn/vim-plug.git
    pull_only: true
    link: none
    location: ~/.config/vim/autoload
    name: vim-plug
    #Mappings were not reimplemented in 10.0?
    #mappings:
      #target_dir: ~/.config/vim/autoload/
      #todo: skip everything else
  - repo: git@github.com:zap-zsh/zap.git
    pull_only: true
    link: none
    location: ~/.local/share/zap
    name: zap
