#!/bin/bash

export BASH_COMPLETION_USER_FILE="$PROFILE_CONFIG_DIR/bash_completion_ext"

# Use bash-completion, if available
# see: https://github.com/scop/bash-completion
# bash_completion_file="/usr/share/bash-completion/bash_completion"
# [[ -f "$bash_completion_file" ]] && . "$bash_completion_file"

source_profile_module "bash_completion_ext"
