#!/bin/bash

# source all user completion files
bash_completion_dir="$SHELL_PROFILE_CONFIG_DIR/bash/bash_completion.d"
for file in "$(find $bash_completion_dir -type f -print)"; do
  [[ -f $file ]] && . "$file" --source-only
done
