#!/bin/sh

# Environment variables -----------------------------------------------
# set XDG
# see specification
# at: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
#
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.var/cache
export XDG_STATE_HOME=$HOME/.var/state
export XDG_RUNTIME_HOME=$HOME/.var/run
# More needed for default Mopidy config to work..
export XDG_CONFIG_DIR=$XDG_CONFIG_HOME
export XDG_DATA_DIR=$XDG_DATA_HOME
export XDG_CACHE_DIR=$XDG_CACHE_HOME

# Preferred character encoding
# export LANG=en_US.utf-8

export EDITOR=vim
export HISTCONTROL=ignoreboth
# 16 KiL
export HISTSIZE=16384
#
# local binaries
export PATH="$HOME/.local/bin:$PATH"
# runit user services
export SVDIR="$HOME/.var/service"


# --------------------------------------------------------------------
# GPG
# see: https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html
# required line for GPG-Agent
export GPG_TTY=$(tty)

# --------------------------------------------------------------------
# Vim
# move vim's stuff out of $HOME
# see: https://tlvince.com/vim-respect-xdg
# and: https://blog.joren.ga/vim-xdg
# move vimrc to ~/.config/vim/vimrc and redirect vim to it at launch.
# export VIMINIT='let $MYVIMRC="${XDG_CONFIG_HOME:-$HOME/.config}/vim/vimrc" | source $MYVIMRC'
export VIMINIT="set nocp | source ${XDG_CONFIG_HOME:-$HOME/.config}/vim/vimrc"

# -------------------------------------------------------------------
# ASDF
export ASDF_CONFIG_FILE="~/.config/asdf/asdfrc"
  # tell flutter where to find install
  # annoying so disabled.
  # export FLUTTER_ROOT="$(asdf where flutter)"

# --------------------------------------------------------------------
# Powerline
# Should also be sourced by non-interative shells!!
# since it will be used to launch wlroots and other wms.
# get powerline-status pipx package install folder
get_pipx_package_location() {
  echo $(pipx runpip $1 show $1 | grep -Po 'Location: \K.*')
}
powerline_package="powerline-status"
pipx_root=$(get_pipx_package_location $powerline_package)
if ! [ -z $pipx_root ]; then
  export POWERLINE_ROOT="$pipx_root/powerline"
fi


# --------------------------------------------------------------------
# Qt
# --------------------------------------------------------------------
# QT/Gnome/GTK theming stuff
# export QT_QPA_PLATFORMTHEME='gnome'
export QT_STYLE_OVERRIDE='kvantum'
# source_shell_file "gtk_settings"
# --------------------------------------------------------------------
# Audio
# for some reason one installation of Ardour doesn't look in user-installed lv2 dir.
export LV2_PATH="${LV2_PATH}:/usr/local/lib/lv2"
#

# vim: ft=sh :
