#!/bin/sh

# At tmux launch, attach to default "main" session
# see: https://unix.stackexchange.com/a/176885
alias tmain="tmux new-session -A -s main"

# some more ls aliases
alias ll='ls -ahlF'
alias la='ls -A'
alias l='ls -CF'
alias lsuuid='lsblk -o NAME,UUID'

# enable color support of ls and also add handy aliases
if [[ "$TERM" =~ .*256color ]]; then
  alias ls='ls -hXF --color=tty'
  alias dir='dir --color=auto'
  alias vdir='vdir --color=auto'
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
  alias tree='tree -C'
fi

# Add an "alert" alias for long running commands.  Use like so:
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias myip="lynx -dump checkip.dyndns.org"

alias df='df -H'
alias du='du -ch'
alias dirs='dirs -v'
alias dmesg='dmesg -HTw'
