#!/bin/sh
# exec chpst -u mopidy:audio \
	# mopidy --config /etc/mopidy/mopidy.conf \
	# >/dev/null 2>&1
[ -r ./conf ] && . ./conf

# TODO logging
mopidy ${OPTS:-} local scan 2>&1
exec mopidy ${OPTS:-} 2>&1

