#!/bin/sh
# exec chpst -u mopidy:audio \
	# mopidy --config /etc/mopidy/mopidy.conf \
	# >/dev/null 2>&1
[ -r ./conf ] && . ./conf

# TODO logging
# TODO don't wait for local scan to launch mopidy (async?), right now restart waits for 7 seconds before giving up.
# TODO create a ./check to report that mopidy is running.
# mopidy ${OPTS:-} local scan 2>&1
exec mopidy ${OPTS:-} 2>&1

