#!/bin/sh

# source: https://github.com/madand/runit-services
# Wait for the PipeWire Pulse daemon to start.
# nope.
# sv check "$HOME/.runit/sv/pipewire-pulse" >/dev/null || exit 1

[ -r ./conf ] && . ./conf

exec mpd --no-daemon --stderr ${OPTS:-} 2>&1

